---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: k3s-janitor
  name: k3s-janitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k3s-janitor
subjects:
- kind: ServiceAccount
  name: k3s-janitor
  namespace: k3s-janitor