apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: k3s-janitor
  name: k3s-janitor
  namespace: "k3s-janitor"
spec:
  selector:
    matchLabels:
      app: k3s-janitor
  template:
    metadata:
      labels:
        app: k3s-janitor
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: k3s-janitor
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
        securityContext:
          allowPrivilegeEscalation: true
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/rancher/
          name: var-lib-rancher
      serviceAccount: k3s-janitor
      serviceAccountName: k3s-janitor
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - hostPath:
          path: /var/lib/rancher/
          type: ""
        name: var-lib-rancher
