---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k3s-janitor-psp-binding
  labels:
    app: k3s-janitor
  namespace: k3s-janitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k3s-janitor-psp
subjects:
- kind: ServiceAccount
  name: k3s-janitor
  namespace: k3s-janitor
- kind: ServiceAccount
  name: default
  namespace: k3s-janitor